logging:
  level:
      root: info
      com.github.bsamartins.springboot.notifications: debug
      org.springframework: info
      org.springframework.cloud: info
      org.springframework.data: info
      org.springframework.beans: info
      org.springframework.security: info
      org.hibernate: off
      org.hibernate.SQL: off
      io.netty: off
      sun: off

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        chat-in:
          destination: chat
          contentType: application/json
        chat-out:
          destination: chat
          contentType: application/json
app:
  security:
    jwt:
      secret: SecretKeyToGenJWTs
      duration: PT1H

redis:
  hostName: localhost
  port: 6379

mongodb:
  hostname: localhost
  port: 27017