logging:
  level:
      root: info
      com.github.bsamartins.springboot.notifications: debug
      org.springframework: info
      org.springframework.data: error
      org.springframework.beans: info
      org.springframework.security: info
      org.hibernate: off
      org.hibernate.SQL: off
      io.netty: off

app:
  security:
    jwt:
      secret: SecretKeyToGenJWTs
      duration: PT1H