version: '3.4'
services:

  config:
    build: ./config/
    image: bsamartins-docker-registry.bintray.io/cloud-microservices/config
    expose:
      - '8888'

  authentication:
    build: ./authentication/
    image: bsamartins-docker-registry.bintray.io/cloud-microservices/authentication
    expose:
      - '8888'

  registry:
    build: ./registry/
    image: bsamartins-docker-registry.bintray.io/cloud-microservices/registry
    expose:
      - '8761'
    ports:
      - 8761:8761
    links:
      - config

  gateway:
    build: ./gateway/
    image: bsamartins-docker-registry.bintray.io/cloud-microservices/gateway
    ports:
      - 9000:8080
    links:
      - registry
      - config

  test-service:
    build: ./test-service/
    image: bsamartins-docker-registry.bintray.io/cloud-microservices/test-service
    expose:
      - 8080
    links:
      - registry
      - config