version: '3.7'
services:
  config:
    image: bsamartins-docker-registry.bintray.io/sandbox-spring-boot-microservices/config
    expose:
      - '8888'

  authentication:
    image: bsamartins-docker-registry.bintray.io/sandbox-spring-boot-microservices/authentication
    expose:
      - '8888'

  registry:
    image: bsamartins-docker-registry.bintray.io/sandbox-spring-boot-microservices/registry
    expose:
      - '8761'
    ports:
      - 8761:8761
    links:
      - config

  gateway:
    image: bsamartins-docker-registry.bintray.io/sandbox-spring-boot-microservices/gateway
    ports:
      - 9000:8080
    links:
      - registry
      - config

  test-service:
    image: bsamartins-docker-registry.bintray.io/sandbox-spring-boot-microservices/test-service
    expose:
      - 8080
    links:
      - registry
      - config